# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ET-WebAPI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Build Api
        run: dotnet build $GITHUB_WORKSPACE/DotnetApi/ET.WebAPI.Api/ -c Release -o ${{env.DOTNET_ROOT}}/builds/api

      - name: Upload api build for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app-build
          path: ${{env.DOTNET_ROOT}}/builds/api
          
      - name: Upload database build for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: database-build
          path: ${{env.DOTNET_ROOT}}/builds/api/ET.WebAPI.Database
          
  migrate-sql-database:
    runs-on: ubuntu-latest
    env:
      SQL_CONNECTION_STRING: 'Server=tcp:${{secrets.SQL_SERVER_URL}},1433;Initial Catalog=${{secrets.SQL_DATABASE_NAME}};Persist Security Info=False;User ID=${{secrets.SQL_LOGIN}};Password=${{secrets.SQL_PASSWORD}};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        
    steps:
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true
          
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Build ET.WebAPI.Database project
        run: dotnet build $GITHUB_WORKSPACE/DotnetApi/ET.WebAPI.Database/ -c Release
          
      - name: Install EF Tool
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
    
      - name: Generate migration SQL script
        run: |
          dotnet ef migrations script \
          --project $GITHUB_WORKSPACE/DotnetApi/ET.WebAPI.Database/ \
          --no-build \
          --idempotent \
          --context ApiDbContext \
          --configuration Release \
          --output ${{env.DOTNET_ROOT}}/sql/sql-script.sql
        
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1
        with:
          server-name: ${{ secrets.SQL_SERVER_URL }}
          connection-string: ${{ env.SQL_CONNECTION_STRING }}
          sql-file: ${{env.DOTNET_ROOT}}/sql/sql-script.sql

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:

#       - name: Download artifact from build job
#         uses: actions/download-artifact@v2
#         with:
#           name: .net-app


#       - name: dotnet publish
#         run: |
#           dotnet publish $GITHUB_WORKSPACE/DotnetApi/ET.WebAPI.Api/ \
#           -c Release \
#           -o ${{env.DOTNET_ROOT}}/DotnetApi \
#           --no-build

#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'ET-WebAPI'
#           slot-name: 'production'
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
#           package: .
